apiVersion: v1
kind: Service
metadata:
  name: prometheus-metrics-example-svc
spec:
  selector:
    app: prometheus-metrics-example
  ports:
    - protocol: TCP
      port: 2112
      targetPort: 2112
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-metrics-example
  name: prometheus-metrics-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-metrics-example
  template:
    metadata:
      labels:
        app: prometheus-metrics-example
    spec:
      containers:
      - name: prometheus-metrics-example
        image: dfinn/prometheus_metrics_example
        ports:
        - name: web
          containerPort: 2112
